### ISSUE TITLE
Deselecting ellipses in concordia view  changes default extents of view.

### ISSUE THREAD

**Issue by bowring** [CIRDLES/CirdlesWebUI#20]
For example, the "reset view" button replots as if the greyed-out ellipses are missing.  One solution would be to not change the extents on de-selection and provide  a second option for  to delete or remove data points altogether that would then change the extents.

**Comment by marottajb** [comment]
This was an issue in [topsoil-js](https://github.com/CIRDLES/topsoil-js) and [Topsoil](https://github.com/CIRDLES/Topsoil), it's been fixed there, but there's still a bug in CirdlesWebUI. Looking into it.
